# Generated by Django 5.1.5 on 2025-01-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmessage',
            old_name='log_data',
            new_name='log_date',
        ),
    ]
